// <auto-generated />
using System;
using GoodHamburger.Orders.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.Orders.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburger.Orders.API.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ds_Nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nr_Telefone");

                    b.HasKey("ClienteId");

                    b.ToTable("tbl_Clientes");
                });

            modelBuilder.Entity("GoodHamburger.Orders.API.Models.ItemPedido", b =>
                {
                    b.Property<int>("ItemPedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Pedido_Item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemPedidoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_Nome");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("id_Pedido");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vl_Preco");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("id_Produto");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("nr_Quantidade");

                    b.HasKey("ItemPedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("tbl_Pedido_Itens");
                });

            modelBuilder.Entity("GoodHamburger.Orders.API.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("id_Cliente");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dt_Criacao");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vl_Desconto");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tp_Status");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vl_SubTotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vl_Total");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("tbl_Pedidos");
                });

            modelBuilder.Entity("GoodHamburger.Orders.API.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Produto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vl_Preco");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tp_Produto");

                    b.HasKey("ProdutoId");

                    b.ToTable("tbl_Produtos");
                });

            modelBuilder.Entity("GoodHamburger.Orders.API.Models.ItemPedido", b =>
                {
                    b.HasOne("GoodHamburger.Orders.API.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodHamburger.Orders.API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GoodHamburger.Orders.API.Models.Pedido", b =>
                {
                    b.HasOne("GoodHamburger.Orders.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GoodHamburger.Orders.API.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
